import { NextRequest, NextResponse } from "next/server";

const GEMINI_API_KEY = process.env.GEMINI_API_KEY || "";
const GEMINI_MODEL = process.env.GEMINI_MODEL || "gemini-2.5-flash";

// Split text into sentences
function splitSentences(text: string): string[] {
  const clean = text.replace(/\s+/g, " ").trim();
  const parts = clean.match(/[^.!?]*[.!?]+(?:\s+|$)|[^.!?]+$/g);
  if (!parts) return [clean];
  return parts.map(s => s.trim()).filter(s => s.length > 0);
}

// Single prompt that does everything: score + analyze
function makePrompt(sentences: string[], fullTextPreview: string): string {
  return `You are an AI detection expert. Analyze this text.

TEXT PREVIEW (first 2000 chars):
${fullTextPreview.slice(0, 2000)}

SENTENCES TO SCORE (numbered):
${sentences.map((s, i) => `[${i}] ${s}`).join("\n")}

PROCESS — follow in order:
1. Score every sentence 0 (clearly human) to 100 (clearly AI).
2. Set overall_score to the rounded mean of the per-sentence scores.
3. Write summary, indicators, and feedback that AGREE with overall_score:
   - overall_score >= 70  → describe AI-like patterns (uniform cadence, generic phrasing, hollow transitions, lack of personal detail). Do NOT call the writing "human", do NOT use phrases like "human authorship" or "natural human voice".
   - overall_score 40-69  → describe a MIX. Use language like "shows AI patterns in places" or "partially humanized".
   - overall_score < 40   → describe human-like patterns (varied rhythm, personal voice, idiosyncratic word choice). Do NOT call the writing AI-generated.
4. indicators MUST list patterns that justify overall_score (AI patterns when high, minor risks when low). NEVER praise human authorship when overall_score >= 70.
5. feedback MUST be actionable for the score (how to humanize when high; how to keep it natural when low).

Respond ONLY with valid JSON:
{
  "scores": [<one 0-100 integer per sentence, exactly ${sentences.length} numbers>],
  "overall_score": <0-100 integer — must equal the rounded mean of scores>,
  "summary": "<2-3 sentences — must agree with overall_score per the rules above>",
  "indicators": ["<specific pattern consistent with overall_score, be detailed>"],
  "feedback": ["<actionable improvement tip, be specific>"]
}

Rules:
- scores array MUST have exactly ${sentences.length} integers.
- summary, indicators, and feedback MUST be consistent with overall_score. Self-contradiction is the worst possible failure.
- Be SPECIFIC: instead of "generic phrasing", say "uses vague words like 'numerous' and 'various' instead of specific examples".
- feedback must be actionable: instead of "be more creative", say "replace 'numerous industries' with specific sectors like 'healthcare diagnostics' or 'supply chain logistics'".
- Output ONLY valid JSON, no markdown.`;
}

// Detect prose that explicitly claims human authorship
function claimsHumanAuthorship(text: string): boolean {
  return /(human authorship|reads as human|clearly human|genuinely human|natural human voice|appears human|sounds human|strong (?:indicators?|signs?) of human|written by a (?:human|person)|authored by a human)/i.test(text);
}

// Detect prose that explicitly claims AI authorship
function claimsAIAuthorship(text: string): boolean {
  return /(ai[- ]?generated|likely ai|machine[- ]generated|appears generated|written by ai|gpt[- ]?generated|generated by (?:a |an )?(?:chatbot|language model|ai)|chatbot[- ]written|language model output)/i.test(text);
}

export async function POST(req: NextRequest) {
  const startTime = Date.now();
  try {
    const { text } = await req.json();
    if (!text || typeof text !== "string") {
      return NextResponse.json({ error: "Text is required" }, { status: 400 });
    }
    if (text.length > 30000) {
      return NextResponse.json({ error: "Text must be under 30,000 characters" }, { status: 400 });
    }
    if (!GEMINI_API_KEY) {
      return NextResponse.json({ error: "Service not configured" }, { status: 500 });
    }

    // Split into sentences — limit to first 60 to fit token budget
    const allSentences = splitSentences(text);
    const MAX_SENTENCES = 60;
    const sentencesToScore = allSentences.slice(0, MAX_SENTENCES);

    // Only send first 3000 chars of text for analysis context (keeps prompt small = faster)
    const prompt = makePrompt(sentencesToScore, text.slice(0, 3000));

    const response = await fetch(
      `https://generativelanguage.googleapis.com/v1beta/models/${GEMINI_MODEL}:generateContent?key=${GEMINI_API_KEY}`,
      {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          contents: [{ role: "user", parts: [{ text: prompt }] }],
          generationConfig: {
            temperature: 0.1,
            maxOutputTokens: 8192,
            responseMimeType: "application/json",
          },
        }),
      }
    );

    if (!response.ok) {
      console.error("Gemini API error:", response.status);
      return NextResponse.json({ error: "AI service temporarily unavailable" }, { status: 502 });
    }

    const data = await response.json();
    const rawText = data.candidates?.[0]?.content?.parts?.[0]?.text;
    if (!rawText) {
      return NextResponse.json({ error: "Failed to analyze text" }, { status: 500 });
    }

    // Parse response
    const cleaned = rawText.replace(/^```[\w]*\s*\n?/i, "").replace(/\n?\s*```\s*$/i, "").trim();
    let parsed: any;
    try {
      parsed = JSON.parse(cleaned);
    } catch {
      const match = cleaned.match(/\{[\s\S]*\}/);
      if (match) {
        try { parsed = JSON.parse(match[0]); } catch {}
      }
    }

    if (!parsed) {
      return NextResponse.json({
        overall_score: 50, human_score: 50,
        summary: "Could not parse analysis. Please try again.",
        sentences: [], indicators: [], feedback: [],
      });
    }

    // Build sentence results
    const scores: number[] = Array.isArray(parsed.scores) ? parsed.scores : [];
    const sentences = sentencesToScore.map((sText, i) => {
      const prob = Math.min(100, Math.max(0, scores[i] ?? 30));
      return {
        text: sText,
        ai_probability: prob,
        highlight: prob >= 70 ? "red" as const : prob >= 30 ? "yellow" as const : "none" as const,
      };
    });

    // Pad for remaining sentences (beyond MAX)
    for (let i = MAX_SENTENCES; i < allSentences.length; i++) {
      sentences.push({ text: allSentences[i], ai_probability: 30, highlight: "none" as const });
    }

    // ─── Overall score: trust per-sentence analysis over holistic guess ───
    // The model can produce a holistic overall_score that drifts from the
    // per-sentence scores it just generated (e.g. 96 overall but a summary
    // describing "human authorship"). Computing the mean from the sentences
    // it actually scored anchors overall_score to its own analysis.
    const scoredSentences = sentences.slice(0, sentencesToScore.length);
    const meanScore = scoredSentences.length > 0
      ? Math.round(
          scoredSentences.reduce((sum, s) => sum + s.ai_probability, 0) /
            scoredSentences.length
        )
      : 50;
    const modelOverall =
      typeof parsed.overall_score === "number" ? parsed.overall_score : meanScore;
    // If the model's holistic score disagrees with the mean by more than 25
    // points, prefer the mean — it's grounded in the per-sentence work.
    const overall_score =
      Math.abs(modelOverall - meanScore) > 25 ? meanScore : modelOverall;

    // ─── Consistency guard for summary ───
    // Even with the mean-anchored score, the model can still produce summary
    // prose that contradicts the score (high score + "human authorship" text,
    // or low score + "AI-generated" text). Catch the contradiction and
    // replace with a templated summary that matches the score.
    let summary: string =
      typeof parsed.summary === "string" && parsed.summary.trim()
        ? parsed.summary.trim()
        : "Analysis completed.";

    const summaryClaimsHuman = claimsHumanAuthorship(summary);
    const summaryClaimsAI = claimsAIAuthorship(summary);

    if (overall_score >= 70 && summaryClaimsHuman && !summaryClaimsAI) {
      summary = `This text shows strong AI-generated patterns (${overall_score}% AI likelihood). The writing exhibits uniform cadence, generic phrasing, and hollow transitions typical of language models. Rework the flagged sentences with personal detail, varied rhythm, and specific examples to read as more human.`;
    } else if (overall_score < 30 && summaryClaimsAI && !summaryClaimsHuman) {
      summary = `This text reads as predominantly human-written (${100 - overall_score}% human-likelihood). It shows the varied rhythm and personal voice typical of human authorship. Only minor sections look AI-influenced.`;
    }

    // ─── Consistency guard for indicators ───
    // If indicators describe human-authorship signals while overall_score is
    // high (or vice versa), fall back to a templated indicator list.
    let indicators: string[] = Array.isArray(parsed.indicators)
      ? parsed.indicators.filter((x: unknown) => typeof x === "string")
      : [];
    const indicatorsContradictHigh =
      overall_score >= 70 &&
      indicators.length > 0 &&
      indicators.every((s) => claimsHumanAuthorship(s) && !claimsAIAuthorship(s));
    if (indicatorsContradictHigh) {
      indicators = [
        "Uniform sentence cadence and length, typical of language model output.",
        "Generic phrasing where specific examples or personal detail would be expected.",
        "Hollow transitions ('moreover', 'furthermore', 'in conclusion') without added meaning.",
      ];
    }

    let feedback: string[] = Array.isArray(parsed.feedback)
      ? parsed.feedback.filter((x: unknown) => typeof x === "string")
      : [];
    if (indicatorsContradictHigh && feedback.length === 0) {
      feedback = [
        "Replace generic terms ('numerous', 'various', 'significant') with specific examples or numbers.",
        "Break up uniform sentence rhythm — mix short, punchy sentences with longer ones.",
        "Add a personal observation, anecdote, or first-person aside to one or two flagged paragraphs.",
      ];
    }

    console.log(
      `Analysis done in ${Date.now() - startTime}ms, ${sentences.length} sentences, score=${overall_score} (model=${modelOverall}, mean=${meanScore})`
    );

    return NextResponse.json({
      overall_score,
      human_score: 100 - overall_score,
      summary,
      sentences,
      indicators,
      feedback,
    });
  } catch (err) {
    console.error("Analysis error:", err, `after ${Date.now() - startTime}ms`);
    return NextResponse.json({ error: "Internal server error" }, { status: 500 });
  }
}
