import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "AI to Human Text Converter — Free Online Tool | EIGEN",
  description:
    "Convert AI-generated text to human writing instantly. Transforms ChatGPT, Claude & Gemini output into natural, readable content. No sign-up.",
  keywords: ["ai to human text", "ai to human text converter", "convert ai text to human", "ai text converter", "ai writing to human writing", "machine text to human text"],
  openGraph: { title: "AI to Human Text Converter — Free Online Tool", description: "Convert AI text to natural human writing instantly. Free, no sign-up.", url: "https://eigentexthumanizer.com/ai-to-human-text", type: "article" },
  alternates: { canonical: "https://eigentexthumanizer.com/ai-to-human-text" },
};

export default function AIToHumanPage() {
  return (
    <main className="min-h-screen bg-[#0a0a0f] text-white">
      <section className="max-w-4xl mx-auto px-4 sm:px-6 pt-16 pb-12">
        <nav className="text-xs text-slate-500 mb-6">
          <Link href="/" className="hover:text-emerald-400 transition-colors">Home</Link><span className="mx-2">/</span><span className="text-slate-400">AI to Human Text</span>
        </nav>
        <h1 className="text-4xl sm:text-5xl font-bold tracking-tight mb-4">
          AI to <span className="text-transparent bg-clip-text bg-gradient-to-r from-emerald-400 to-cyan-400">Human</span> Text Converter
        </h1>
        <p className="text-lg text-slate-400 max-w-2xl mb-8">
          Convert AI-generated text to natural human writing. Paste content from ChatGPT, Claude, Gemini, or any AI tool and get back text that sounds like a real person wrote it. Free, instant, no sign-up.
        </p>
        <Link href="/" className="inline-flex px-6 py-3 bg-gradient-to-r from-emerald-500 to-cyan-500 rounded-xl text-sm font-medium hover:from-emerald-400 hover:to-cyan-400 transition-all">
          Convert Now — Free →
        </Link>
      </section>

      <section className="max-w-4xl mx-auto px-4 sm:px-6 py-12 border-t border-white/5">
        <h2 className="text-2xl font-bold mb-6">Why Convert AI to Human Text?</h2>
        <div className="grid sm:grid-cols-3 gap-5">
          {[
            { title: "Natural Flow", desc: "AI text is grammatically correct but often reads unnaturally. Converting it adds the rhythm and flow of real human writing." },
            { title: "Pass Detection", desc: "Schools and workplaces use AI detectors. Human-converted text naturally passes these checks without looking suspicious." },
            { title: "Your Voice", desc: "Make the text sound like you wrote it — with your personal style, word choices, and natural imperfections that make writing authentic." },
          ].map((item) => (
            <div key={item.title} className="p-5 rounded-xl bg-white/[0.02] border border-white/5">
              <h3 className="text-sm font-semibold text-emerald-400 mb-2">{item.title}</h3>
              <p className="text-xs text-slate-400 leading-relaxed">{item.desc}</p>
            </div>
          ))}
        </div>
      </section>

      <section className="max-w-4xl mx-auto px-4 sm:px-6 py-12 border-t border-white/5">
        <h2 className="text-2xl font-bold mb-6">Before & After</h2>
        <div className="grid sm:grid-cols-2 gap-4">
          <div className="p-5 rounded-xl bg-red-500/5 border border-red-500/20">
            <div className="text-[10px] uppercase tracking-widest text-red-400/60 mb-3">AI-Generated</div>
            <p className="text-sm text-slate-300 leading-relaxed italic">
              "Furthermore, it is important to note that artificial intelligence has significantly impacted various industries. In conclusion, the implementation of AI technologies has resulted in increased efficiency and productivity across multiple sectors."
            </p>
          </div>
          <div className="p-5 rounded-xl bg-emerald-500/5 border border-emerald-500/20">
            <div className="text-[10px] uppercase tracking-widest text-emerald-400/60 mb-3">Humanized</div>
            <p className="text-sm text-slate-300 leading-relaxed">
              "AI's been shaking things up across pretty much every industry you can think of. Companies are getting more done in less time — it's honestly wild how much has changed in just a few years."
            </p>
          </div>
        </div>
      </section>

      <section className="max-w-4xl mx-auto px-4 sm:px-6 py-12 border-t border-white/5">
        <h2 className="text-2xl font-bold mb-6">FAQ</h2>
        <div className="space-y-4">
          {[
            { q: "What is an AI to human text converter?", a: "It's a tool that takes text generated by AI (like ChatGPT or Claude) and rewrites it to sound like natural human writing — with varied sentence structures, conversational tone, and authentic language patterns." },
            { q: "Is the AI to human text converter free?", a: "Yes! You get 3 free conversions per day. No sign-up or credit card needed." },
            { q: "Does it work in other languages?", a: "Our tool preserves the original language of your input. It works with English, Spanish, French, German, and many other languages." },
          ].map((faq) => (
            <details key={faq.q} className="group bg-white/[0.02] border border-white/5 rounded-xl">
              <summary className="px-5 py-4 cursor-pointer text-sm font-medium hover:text-emerald-400 transition-colors list-none flex justify-between items-center">
                {faq.q} <span className="text-slate-500 group-open:rotate-180 transition-transform">▼</span>
              </summary>
              <p className="px-5 pb-4 text-xs text-slate-400 leading-relaxed">{faq.a}</p>
            </details>
          ))}
        </div>
      </section>

      <section className="max-w-4xl mx-auto px-4 sm:px-6 py-16 text-center border-t border-white/5">
        <h2 className="text-2xl font-bold mb-3">Convert AI Text to Human Writing</h2>
        <p className="text-sm text-slate-400 mb-6">Free. Instant. No sign-up required.</p>
        <Link href="/" className="inline-flex px-8 py-3 bg-gradient-to-r from-emerald-500 to-cyan-500 rounded-xl text-sm font-medium hover:from-emerald-400 hover:to-cyan-400 transition-all">
          Convert Now — Free
        </Link>
      </section>

      <footer className="border-t border-white/5 py-6 text-center text-[10px] text-slate-600">© 2026 EIGEN</footer>
    </main>
  );
}
