import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "ChatGPT Detector — Free Tool to Detect ChatGPT Written Text",
  description:
    "Free ChatGPT detector with sentence-level analysis. Detect ChatGPT, GPT-4, and GPT-4o text. Color-coded highlights. No sign-up needed.",
  keywords: ["chatgpt detector", "detect chatgpt", "chatgpt text detector", "gpt-4 detector", "gpt detector", "is this chatgpt", "chatgpt checker", "openai detector"],
  openGraph: { title: "ChatGPT Detector — Free Tool to Detect ChatGPT Text", description: "Check if text was written by ChatGPT with sentence-level analysis.", url: "https://eigentexthumanizer.com/chatgpt-detector", type: "article" },
  alternates: { canonical: "https://eigentexthumanizer.com/chatgpt-detector" },
};

export default function ChatGPTDetectorPage() {
  return (
    <main className="min-h-screen bg-[#0a0a0f] text-white">
      <section className="max-w-4xl mx-auto px-4 sm:px-6 pt-16 pb-12">
        <nav className="text-xs text-slate-500 mb-6">
          <Link href="/" className="hover:text-emerald-400 transition-colors">Home</Link><span className="mx-2">/</span><span className="text-slate-400">ChatGPT Detector</span>
        </nav>
        <h1 className="text-4xl sm:text-5xl font-bold tracking-tight mb-4">
          <span className="text-transparent bg-clip-text bg-gradient-to-r from-amber-400 to-orange-400">ChatGPT</span> Detector
        </h1>
        <p className="text-lg text-slate-400 max-w-2xl mb-8">
          Detect text written by ChatGPT, GPT-4, and GPT-4o. Get instant sentence-by-sentence analysis showing exactly which parts were generated by OpenAI's models. Free and accurate.
        </p>
        <Link href="/?tab=detector" className="inline-flex px-6 py-3 bg-gradient-to-r from-amber-500 to-orange-500 rounded-xl text-sm font-medium hover:from-amber-400 hover:to-orange-400 transition-all">
          Detect ChatGPT Text →
        </Link>
      </section>

      <section className="max-w-4xl mx-auto px-4 sm:px-6 py-12 border-t border-white/5">
        <h2 className="text-2xl font-bold mb-6">How to Detect ChatGPT Writing</h2>
        <div className="grid sm:grid-cols-2 gap-6">
          {[
            { title: "Uniform Sentence Length", desc: "ChatGPT tends to write sentences of similar length. Human writing naturally varies between short and long sentences." },
            { title: "Formulaic Transitions", desc: "Phrases like 'Furthermore,' 'Moreover,' and 'In conclusion' appear disproportionately often in ChatGPT output." },
            { title: "Lack of Contractions", desc: "ChatGPT defaults to formal writing without contractions (don't, can't, it's), unlike most human writers." },
            { title: "Overly Balanced Structure", desc: "ChatGPT often presents perfectly balanced arguments with 'On one hand... On the other hand' patterns." },
          ].map((item) => (
            <div key={item.title} className="p-4 rounded-xl bg-white/[0.02] border border-white/5">
              <h3 className="text-sm font-semibold text-amber-400 mb-1">{item.title}</h3>
              <p className="text-xs text-slate-400">{item.desc}</p>
            </div>
          ))}
        </div>
      </section>

      <section className="max-w-4xl mx-auto px-4 sm:px-6 py-12 border-t border-white/5">
        <h2 className="text-2xl font-bold mb-6">FAQ</h2>
        <div className="space-y-4">
          {[
            { q: "How do I know if text is written by ChatGPT?", a: "Look for patterns like uniform sentence lengths, excessive use of transition words, lack of contractions, and perfectly structured paragraphs. Our detector analyzes these patterns automatically and gives you a probability score." },
            { q: "Can ChatGPT-generated text be detected?", a: "Yes. While ChatGPT produces grammatically perfect text, it has distinctive patterns that differ from human writing. Our detector identifies these patterns at the sentence level." },
            { q: "Is the ChatGPT detector free?", a: "Yes! You get 3 free scans per day. For more scans, upgrade to a paid plan starting at $9.99/mo." },
          ].map((faq) => (
            <details key={faq.q} className="group bg-white/[0.02] border border-white/5 rounded-xl">
              <summary className="px-5 py-4 cursor-pointer text-sm font-medium hover:text-amber-400 transition-colors list-none flex justify-between items-center">
                {faq.q} <span className="text-slate-500 group-open:rotate-180 transition-transform">▼</span>
              </summary>
              <p className="px-5 pb-4 text-xs text-slate-400 leading-relaxed">{faq.a}</p>
            </details>
          ))}
        </div>
      </section>

      <section className="max-w-4xl mx-auto px-4 sm:px-6 py-16 text-center border-t border-white/5">
        <h2 className="text-2xl font-bold mb-3">Detect ChatGPT Text Now</h2>
        <p className="text-sm text-slate-400 mb-6">Free, instant, sentence-level analysis.</p>
        <Link href="/?tab=detector" className="inline-flex px-8 py-3 bg-gradient-to-r from-amber-500 to-orange-500 rounded-xl text-sm font-medium hover:from-amber-400 hover:to-orange-400 transition-all">
          Scan for ChatGPT — Free
        </Link>
      </section>

      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify({
        "@context": "https://schema.org", "@type": "FAQPage", mainEntity: [
          { "@type": "Question", name: "How do I know if text is written by ChatGPT?", acceptedAnswer: { "@type": "Answer", text: "Look for patterns like uniform sentence lengths, excessive transition words, and lack of contractions. Our detector analyzes these automatically." } },
          { "@type": "Question", name: "Can ChatGPT-generated text be detected?", acceptedAnswer: { "@type": "Answer", text: "Yes. ChatGPT has distinctive patterns that differ from human writing. Our detector identifies these at the sentence level." } },
        ],
      }) }} />

      <footer className="border-t border-white/5 py-6 text-center text-[10px] text-slate-600">© 2026 EIGEN</footer>
    </main>
  );
}
